swagger:
  basepackage: com.cn.chen.distributed.order.config  #扫描api包路径扫描SwaggerConfig2.java所在api包路径
  service:
    name: consumer-feign #api名称
    description: consumer-feign资源服务 #api描述
    developer: 陈亮 #api开发者
  auth:
    server:   #使用哪种认证方式,我这里没填
  is:
    enable: true #是否激活swagger开
